# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@6.3.0

jobs:
  lint_build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
            pkg-manager: yarn
      - run:
          command: yarn lint
          name: Lint app
      - run:
          command: yarn build
          name: Build app


workflows:
  test-workflow:
    jobs:
      - lint_build
